#info:
#  component: Zuul Server
  
#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false

zuul:
  routes:
    user-ui:
      path: /users/**
      serviceId: user-ui
      strip-prefix: false

server:
  port: 8085


spring:
  application:
    name: gateway
